services:
  gobitmq:
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      GOBITMQ_MGMT_ALLOW_REMOTE: "true"
      GOBITMQ_MGMT_USERS: "admin:admin123:admin"
    volumes:
      - gobitmq-data:/data

volumes:
  gobitmq-data:
